// AUTO-GENERATED by scripts/generate-icons.js. DO NOT EDIT.

import * as React from 'react'
import KeyboardArrowDownIcon from './keyboard_arrow_down.svg';
import KeyboardArrowLeftIcon from './keyboard_arrow_left.svg';

export { KeyboardArrowDownIcon, KeyboardArrowLeftIcon }

export type IconName = 'keyboard_arrow_down' | 'keyboard_arrow_left';

export const iconMap: Record<IconName, React.FC<React.SVGProps<SVGSVGElement>>> = {
  'keyboard_arrow_down': KeyboardArrowDownIcon,
  'keyboard_arrow_left': KeyboardArrowLeftIcon,
};